spring:
  h2:
    console.enabled: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
    username: robot
    password: robot
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
server:
  servlet:
    context-path: /api/v1